apiVersion: apps/v1
kind: Deployment
metadata:
  name: crud-app        # ✅ Match with pipeline
  namespace: crud-app
  labels:
    app: crud-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: crud-app
  template:
    metadata:
      labels:
        app: crud-app
    spec:
      containers:
        - name: crud-app        # ✅ Match with pipeline
          image: softconsist/crud-123:latest
          ports:
            - containerPort: 3000

