apiVersion: v1
kind: Service
metadata:
  namespace: crud-app
  name: crud-app-service
spec:
  selector:
    app: crud-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer

