name: CI/CD Pipeline

on:
  push:
    branches: ["1"]
  pull_request:
  workflow_dispatch:

jobs:
  # ---------------- SonarCloud + Tests ----------------
  code-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run Tests with Coverage
        run: npm test -- --coverage

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          args: >
            -Dsonar.organization=ashubambal
            -Dsonar.projectKey=ashubambal_crud-app
            -Dsonar.sources=.
            -Dsonar.branch.name=main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  # ---------------- Docker Build & Push ----------------
  docker-build-push:
    runs-on: ubuntu-latest
    needs: code-analysis
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: softconsist/crud-123:latest

  # ---------------- Deploy to EC2 ----------------
  deploy-ec2:
    runs-on: ubuntu-latest
    needs: docker-build-push
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker rm -f $(docker ps -q) || true
            docker pull softconsist/crud-123:latest
            docker run -d -p 3000:3000 --name crud-app softconsist/crud-123:latest
